### ISSUE TITLE
Android build error (release build)

### ISSUE THREAD

**Issue by GenKawamura** [HappyFaceGoettingen/HappyFace-MadMask#11]
It looks, the automatic build in the release build fails. As for debug build, it's OK:

The cause is a missing class of "HomePage in /tmp/HappyFaceMobile-build/src/pages/home/_home.ts".

http://141.5.108.29:20100/data/ADC/log/madmask.android-build.log
[2K[GRunning app-scripts build: --prod --platform android --target cordova
[21:14:56]  build prod started ... 
[21:14:57]  clean started ... 
[21:14:57]  clean finished in 13 ms 
[21:14:57]  copy started ... 
[21:14:57]  deeplinks started ... 
[21:14:57]  deeplinks finished in 423 ms 
[21:14:57]  ngc started ... 
[21:15:12]  typescript error 
            Cannot determine the module for class HomePage in /tmp/HappyFaceMobile-build/src/pages/home/_home.ts! Add 
            HomePage to the NgModule to fix it. 

[2K[GError: The Angular AoT build failed. See the issues above
    at /tmp/HappyFaceMobile-build/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/tmp/HappyFaceMobile-build/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/tmp/HappyFaceMobile-build/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/tmp/HappyFaceMobile-build/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
[21:15:13]  copy finished in 15.92 s

**Comment by GenKawamura** [comment]
The error occurs in the latest tomon_development branch (574db4fb025aa78dc692d0049f49b484316369ae)
